# Pandas 실전연습
아마존 사이트에서 구입한 이력 데이터를 Pandas로 가져와 분석해봅시다.

## 1. 데이터 로드 및 확인

In [3]:
import pandas as pd
df = pd.read_csv('./Desktop/dataset/purchase.csv')
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [5]:
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

In [7]:
df.tail(100)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9900,"881 Julie Orchard Suite 722\nNorth Jonathan, O...",94 yV,PM,Opera/9.22.(Windows NT 6.0; it-IT) Presto/2.9....,"Anderson, Little and Parker",30035348786641,06/23,31,VISA 16 digit,harriscarl@dominguez.com,Mining engineer,19.11.202.68,fr,75.86
9901,"908 Norman Burgs\nPhillipsberg, VT 92023-9956",90 Ng,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Hughes Inc,30148833294789,09/20,483,Voyager,james32@gmail.com,Meteorologist,250.66.85.29,en,57.25
9902,"94713 Noah Glens\nJosephshire, GA 02992-4583",86 cE,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4)...,Krause Group,869935222782234,02/23,281,Mastercard,paultorres@gardner-chandler.com,"Administrator, arts",212.159.147.187,es,52.77
9903,"883 Courtney Dale Apt. 274\nTimothyside, SC 07...",41 hi,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows CE;...,"Pitts, Ware and Ross",30340551207214,07/26,210,VISA 16 digit,denise42@gmail.com,"Journalist, broadcasting",148.2.85.27,es,94.26
9904,"4571 Cheryl Loaf Apt. 273\nThomasmouth, OH 14568",76 qZ,PM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,"Guzman, Nelson and Salazar",378455572445450,10/16,780,VISA 16 digit,vromero@smith.biz,Financial planner,127.142.123.127,pt,46.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [9]:
df.describe()

        Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

In [11]:
df.columns # 명확히 컬럼명을 확인해야함.

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [12]:
df.columns[0]

'Address'

In [13]:
df['Address']

0       16629 Pace Camp Apt. 448\nAlexisborough, NE 77...
1       9374 Jasmine Spurs Suite 508\nSouth John, TN 8...
2                        Unit 0065 Box 5052\nDPO AP 27450
3                   7780 Julia Fords\nNew Stacy, WA 45798
4       23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...
                              ...
9995        966 Castaneda Locks\nWest Juliafurt, CO 96415
9996    832 Curtis Dam Suite 785\nNorth Edwardburgh, T...
9997                Unit 4434 Box 6343\nDPO AE 28026-0283
9998                 0096 English Rest\nRoystad, IA 12457
9999       40674 Barrett Stravenue\nGrimesville, WI 79682
Name: Address, Length: 10000, dtype: object

In [14]:
df[df.columns[0]]

0       16629 Pace Camp Apt. 448\nAlexisborough, NE 77...
1       9374 Jasmine Spurs Suite 508\nSouth John, TN 8...
2                        Unit 0065 Box 5052\nDPO AP 27450
3                   7780 Julia Fords\nNew Stacy, WA 45798
4       23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...
                              ...
9995        966 Castaneda Locks\nWest Juliafurt, CO 96415
9996    832 Curtis Dam Suite 785\nNorth Edwardburgh, T...
9997                Unit 4434 Box 6343\nDPO AE 28026-0283
9998                 0096 English Rest\nRoystad, IA 12457
9999       40674 Barrett Stravenue\nGrimesville, WI 79682
Name: Address, Length: 10000, dtype: object

In [15]:
df.shape

(10000, 14)

In [16]:
df.iloc[0]   # 행 단위로 접근   # 인덱스 기준

Address             16629 Pace Camp Apt. 448\nAlexisborough, NE 77...
Lot                                                             46 in
AM or PM                                                           PM
Browser Info        Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...
Company                                               Martinez-Herman
Credit Card                                          6011929061123406
CC Exp Date                                                     02/20
CC Security Code                                                  900
CC Provider                                              JCB 16 digit
Email                                               pdunlap@yahoo.com
Job                            Scientist, product/process development
IP Address                                            149.146.147.205
Language                                                           el
Purchase Price                                                  98.14
Name: 0, dtype: object

In [17]:
df.loc[0]  # (위치 기준)

Address             16629 Pace Camp Apt. 448\nAlexisborough, NE 77...
Lot                                                             46 in
AM or PM                                                           PM
Browser Info        Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...
Company                                               Martinez-Herman
Credit Card                                          6011929061123406
CC Exp Date                                                     02/20
CC Security Code                                                  900
CC Provider                                              JCB 16 digit
Email                                               pdunlap@yahoo.com
Job                            Scientist, product/process development
IP Address                                            149.146.147.205
Language                                                           el
Purchase Price                                                  98.14
Name: 0, dtype: object

In [18]:
df[5:10].iloc[0]

Address             7502 Powell Mission Apt. 768\nTravisland, VA 3...
Lot                                                             21 XT
AM or PM                                                           PM
Browser Info        Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...
Company                                                Silva-Anderson
Credit Card                                            30246185196287
CC Exp Date                                                     07/25
CC Security Code                                                 7169
CC Provider                                                  Discover
Email                                               ynguyen@gmail.com
Job                                                 Fish farm manager
IP Address                                              55.96.152.147
Language                                                           ru
Purchase Price                                                  25.15
Name: 5, dtype: object

In [20]:
df[5:10].loc[5]

Address             7502 Powell Mission Apt. 768\nTravisland, VA 3...
Lot                                                             21 XT
AM or PM                                                           PM
Browser Info        Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...
Company                                                Silva-Anderson
Credit Card                                            30246185196287
CC Exp Date                                                     07/25
CC Security Code                                                 7169
CC Provider                                                  Discover
Email                                               ynguyen@gmail.com
Job                                                 Fish farm manager
IP Address                                              55.96.152.147
Language                                                           ru
Purchase Price                                                  25.15
Name: 5, dtype: object

In [21]:
df['AM or PM'].unique()

array(['PM', 'AM'], dtype=object)

In [22]:
df['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [23]:
df['AM or PM'] == 'PM'

0        True
1        True
2        True
3        True
4       False
        ...
9995     True
9996    False
9997    False
9998     True
9999    False
Name: AM or PM, Length: 10000, dtype: bool

In [24]:
df[df['AM or PM'] == 'PM']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84

In [25]:
len(df[df['AM or PM'] == 'PM'])

5068

- 구매 금액의 평균을 구해보세요.
- 웹사이트 언어로 영어(en)를 쓰는 사람은 몇명인가요??
- 고객들의 직업은 어떤 종류가 있나요?
- 고객들의 직업별 구매금액의 평균값은 어떻게 되나요?
- 고객들의 직업별 구매금액의 합이 가장 큰 직업은 무엇인가요?
- bondellen@williams-garza.com 이메일 주소를 가진 사용자의 구매 이력을 찾아보세요.
- Mastercard를 사용했으며 50달러 이상 구매한 사용자는 몇명인가요?
- Windows OS를 사용하는 사용자는 몇명인가요?

In [26]:
df['Purchase Price'].mean()

50.34730200000025

In [28]:
len(df[df['Language'] == 'en'])

1098

In [30]:
df['Job'].unique()

array(['Scientist, product/process development', 'Drilling engineer',
       'Customer service manager', 'Fine artist', 'Fish farm manager',
       'Dancer', 'Event organiser', 'Financial manager',
       'Forensic scientist', 'Development worker, community',
       'Diagnostic radiographer', 'Surveyor, quantity',
       'Accountant, chartered public finance', 'Acupuncturist',
       'Retail manager', 'Therapist, art', 'Designer, jewellery',
       'Photographer', 'Designer, interior/spatial',
       'Public relations officer', 'Presenter, broadcasting',
       'Field seismologist', 'Musician',
       'Training and development officer', "Barrister's clerk",
       'Careers adviser', 'Scientist, research (life sciences)',
       'Recycling officer', 'Fisheries officer', 'Sales executive',
       'Civil Service fast streamer', 'Theatre stage manager',
       'Therapist, music', 'Lecturer, further education',
       'Animal technologist', 'Psychologist, occupational',
       'Music therapist', 'Minerals surveyor',
       'Tourist information centre manager', 'Tax inspector',
       'Buyer, industrial', 'Purchasing manager', 'Heritage manager',
       'Games developer', 'Facilities manager', 'Chemist, analytical',
       'Horticulturist, amenity', 'Mechanical engineer',
       'Clinical research associate', 'Technical author',
       'Radio broadcast assistant', 'Engineer, broadcasting (operations)',
       'Clothing/textile technologist', 'Holiday representative',
       'Housing manager/officer', 'Teacher, special educational needs',
       'Engineer, agricultural', 'Buyer, retail',
       'Doctor, general practice', 'Hotel manager',
       'Engineer, civil (consulting)', 'General practice doctor',
       'Jewellery designer', 'Therapist, speech and language',
       'Operational researcher', 'Graphic designer',
       'Editorial assistant', 'Financial adviser', 'Paramedic',
       'Secretary, company', 'Paediatric nurse',
       'Data processing manager', 'Print production planner',
       'Engineer, materials', 'Economist', 'Designer, furniture',
       'Human resources officer', 'Administrator',
       'Teacher, secondary school', 'Video editor',
       'Chartered certified accountant',
       'Teacher, English as a foreign language', 'Airline pilot',
       'Engineer, land', 'Legal secretary', 'Administrator, arts',
       'Dealer', 'Town planner', 'Travel agency manager',
       'Engineer, water', 'Lecturer, higher education',
       'Higher education careers adviser', 'Intelligence analyst',
       'Technical sales engineer', 'Dietitian',
       'International aid/development worker',
       'Learning disability nurse', 'Geneticist, molecular',
       'Optometrist', 'Building surveyor', 'Sports therapist',
       'Geophysical data processor', 'Multimedia programmer',
       'Research scientist (maths)', 'Social worker', 'Camera operator',
       'Interpreter', 'Furniture designer', 'Commercial horticulturist',
       'Surgeon', 'Psychotherapist, dance movement',
       'Information systems manager', 'Music tutor',
       'Merchandiser, retail', 'Insurance risk surveyor',
       'Armed forces operational officer', 'Homeopath',
       'Animal nutritionist', 'Tourism officer', 'Cabin crew',
       'Psychiatric nurse', 'Magazine features editor',
       'Chartered management accountant', 'Market researcher',
       'Mudlogger', 'Textile designer', 'Restaurant manager, fast food',
       'Medical laboratory scientific officer',
       'Chartered public finance accountant', 'Financial trader',
       'Scientist, marine', 'Environmental manager',
       'Community education officer', 'Solicitor',
       'Psychologist, clinical', 'Occupational therapist',
       'Retail merchandiser', 'Mental health nurse', 'Ophthalmologist',
       'Insurance underwriter', 'Engineer, aeronautical',
       'Chartered accountant', 'Environmental health practitioner',
       'Research scientist (life sciences)', 'Wellsite geologist',
       'Product designer', 'Armed forces technical officer',
       'Television/film/video producer', 'Water quality scientist',
       'Furniture conservator/restorer', 'Radio producer',
       'Programmer, multimedia', 'Scientist, biomedical',
       'Psychologist, sport and exercise', 'Merchant navy officer',
       'Designer, television/film set', 'Engineering geologist',
       'Health and safety inspector', 'Naval architect', 'Chiropodist',
       'Engineer, chemical', 'Scientist, research (medical)',
       'Personal assistant', 'Retail banker',
       'Advertising account planner', 'Art therapist',
       'Forest/woodland manager', 'Research scientist (medical)',
       'Scientific laboratory technician', 'Licensed conveyancer',
       'Engineer, building services', 'Energy engineer', 'Teacher, music',
       'Oncologist', 'Brewing technologist', 'Community arts worker',
       'Therapist, drama', 'Water engineer', 'Software engineer',
       'Geochemist', 'Designer, industrial/product',
       'Nature conservation officer',
       'Production designer, theatre/television/film',
       'Commercial art gallery manager', 'Exhibition designer',
       'Education officer, environmental',
       'Runner, broadcasting/film/video', 'Pharmacist, hospital',
       'Doctor, hospital', 'Teacher, adult education', 'Sub',
       'Podiatrist', 'Air broker', 'Engineer, civil (contracting)',
       'Lexicographer', 'Speech and language therapist',
       'Catering manager', 'Colour technologist', 'Surveyor, building',
       'Agricultural consultant', 'Horticultural therapist',
       'Pension scheme manager', 'Theatre manager', 'Producer, radio',
       'Scientist, forensic', 'Surveyor, insurance',
       'Hospital pharmacist', 'Surveyor, rural practice',
       'Industrial/product designer', 'Corporate treasurer',
       'Structural engineer', 'Research officer, trade union',
       'Pensions consultant', 'Secretary/administrator', 'Firefighter',
       'Database administrator', 'Health promotion specialist',
       'Operations geologist', 'Regulatory affairs officer',
       'Production assistant, radio', 'Press sub',
       'Education administrator', 'Biomedical scientist', 'Tour manager',
       'Midwife', 'Television floor manager', 'Mining engineer',
       'Interior and spatial designer', 'Engineer, energy',
       'Publishing rights manager', 'Manufacturing systems engineer',
       'Designer, exhibition/display',
       'Control and instrumentation engineer', 'Ergonomist',
       'Scientist, research (maths)', 'Psychologist, forensic',
       'Clinical scientist, histocompatibility and immunogenetics',
       'Accommodation manager', 'Administrator, sports',
       'Sports development officer', 'Educational psychologist',
       'Social research officer, government', 'Quarry manager',
       'Medical sales representative', 'Consulting civil engineer',
       'Trade union research officer', 'Financial planner',
       'Futures trader', 'Medical illustrator', 'Engineer, structural',
       'Transport planner', 'Special educational needs teacher',
       'Chiropractor', 'Therapist, sports',
       'Scientist, research (physical sciences)', 'Site engineer',
       'Psychologist, counselling', 'Bonds trader', 'Banker',
       'Proofreader', 'Social researcher', 'Analytical chemist',
       'Dramatherapist', 'Editor, commissioning', 'Sports administrator',
       'Sport and exercise psychologist', 'Garment/textile technologist',
       'Engineer, maintenance (IT)', 'Surveyor, building control',
       'Media planner', 'Statistician', 'Food technologist',
       'Chartered loss adjuster', 'Petroleum engineer',
       'Engineer, maintenance', 'Television camera operator',
       'Geoscientist', 'Printmaker', 'Artist', 'Hospital doctor',
       'Systems analyst', 'Radiographer, therapeutic',
       'Freight forwarder', 'Call centre manager', 'Theatre director',
       'Occupational psychologist', 'Communications engineer',
       'Land/geomatics surveyor', 'Advertising account executive',
       'Civil engineer, consulting', 'Medical secretary',
       'IT technical support officer', 'Advice worker',
       'Visual merchandiser', 'Nurse, mental health',
       'Further education lecturer', 'Investment banker, corporate',
       'Bookseller', 'Engineer, production', 'Health visitor',
       'Archivist', 'Recruitment consultant',
       'Conservator, museum/gallery', 'Translator', 'Youth worker',
       'Operational investment banker',
       'Radiation protection practitioner',
       'Research officer, political party', 'Make',
       'Horticulturist, commercial', 'Surveyor, hydrographic',
       'Engineer, communications', 'Surveyor, minerals', 'Hydrologist',
       'Race relations officer', 'Quantity surveyor',
       'Geologist, wellsite', 'Museum/gallery conservator',
       'Community pharmacist', 'Adult guidance worker',
       'Building control surveyor', 'Museum/gallery exhibitions officer',
       'Ambulance person', 'Probation officer', 'Orthoptist',
       'Charity officer', 'Risk analyst', 'Best boy',
       'Arts administrator',
       'Lighting technician, broadcasting/film/video',
       'Engineer, drilling', 'Engineer, control and instrumentation',
       'Medical physicist', 'Dispensing optician',
       'Management consultant', 'Commercial/residential surveyor',
       'English as a foreign language teacher', 'Engineer, site',
       'Automotive engineer', 'Air traffic controller', 'Lawyer',
       'Contracting civil engineer', 'Psychotherapist, child',
       'Maintenance engineer', 'Science writer',
       'Administrator, education', 'Administrator, Civil Service',
       'Estate manager/land agent', 'Company secretary',
       'Therapist, horticultural', 'Broadcast engineer',
       'Sound technician, broadcasting/film/video',
       'Private music teacher', 'Engineer, manufacturing',
       'Emergency planning/management officer', 'Risk manager',
       'IT consultant', 'Geographical information systems officer',
       'Equities trader', 'Immigration officer',
       'Therapeutic radiographer', 'Curator', 'Child psychotherapist',
       'Advertising art director', 'Forensic psychologist',
       'Hydrographic surveyor', 'Immunologist', 'Sports coach',
       'Haematologist', 'Waste management officer',
       'Conservator, furniture', 'Research officer, government',
       'Agricultural engineer', 'IT sales professional',
       'Armed forces logistics/support/administrative officer',
       'Field trials officer', 'Psychotherapist', 'Air cabin crew',
       'Psychiatrist', 'Illustrator', 'Marine scientist',
       'Multimedia specialist', 'Cytogeneticist',
       'Occupational hygienist', 'Charity fundraiser',
       'Planning and development surveyor', 'Counselling psychologist',
       'Physicist, medical', 'TEFL teacher',
       'Research scientist (physical sciences)', 'Fashion designer',
       'Engineer, petroleum', 'Tree surgeon',
       'Corporate investment banker', 'Public house manager',
       'Designer, textile', 'Public librarian',
       'Arts development officer', 'Actor', 'Hydrogeologist',
       'Production assistant, television', 'Embryologist, clinical',
       'Press photographer', 'Marketing executive',
       'Television production assistant', 'Early years teacher',
       'Landscape architect', 'Librarian, academic', 'Web designer',
       'Health service manager', 'Clinical psychologist',
       'Exercise physiologist', 'Electrical engineer',
       'Psychologist, prison and probation services',
       'Journalist, magazine', 'Dance movement psychotherapist',
       'Animator', 'Legal executive', 'Plant breeder/geneticist',
       'Manufacturing engineer', 'Microbiologist', 'Biochemist, clinical',
       'Broadcast presenter', 'Ranger/warden',
       'Programme researcher, broadcasting/film/video', 'Dentist',
       'Aid worker', 'Publishing copy', 'Environmental education officer',
       'Librarian, public', 'Phytotherapist', 'Nurse, adult',
       'Programmer, systems', 'Scientist, physiological',
       'Secondary school teacher', 'Media buyer', 'Trade mark attorney',
       'Editor, film/video', 'Careers information officer',
       'Retail buyer', 'Ship broker', 'Lobbyist', 'Location manager',
       'Surveyor, mining', 'Systems developer', 'Optician, dispensing',
       'Chemical engineer', 'Oceanographer', 'Patent attorney',
       'Passenger transport manager', 'Glass blower/designer',
       'Psychologist, educational', 'Education officer, museum',
       'Patent examiner', 'Logistics and distribution manager',
       'Trading standards officer', 'Seismic interpreter',
       'Local government officer', 'Clinical cytogeneticist',
       'Biomedical engineer', 'Diplomatic Services operational officer',
       'Land', 'Surveyor, planning and development', 'Farm manager',
       'Claims inspector/assessor', 'Warden/ranger',
       'Civil engineer, contracting', 'Clinical molecular geneticist',
       'Surveyor, land/geomatics', 'Therapist, nutritional',
       'Historic buildings inspector/conservation officer',
       'English as a second language teacher', 'Materials engineer',
       'Insurance broker', 'Ecologist', 'Production manager',
       'Veterinary surgeon', 'Pilot, airline', "Nurse, children's",
       'Astronomer', 'Architect', 'Conservation officer, nature',
       'Personnel officer', 'Network engineer', 'Investment analyst',
       'Writer', 'Designer, fashion/clothing', 'Theme park manager',
       'Engineer, electrical', 'Art gallery manager', 'Office manager',
       'Pharmacologist', 'Meteorologist', 'Estate agent',
       "Politician's assistant", 'Environmental consultant', 'Osteopath',
       'Amenity horticulturist', 'Physiological scientist',
       'Public relations account executive',
       'Senior tax professional/tax inspector', 'Arboriculturist',
       'Radiographer, diagnostic', 'Engineer, automotive',
       'Editor, magazine features', 'Sales professional, IT',
       'Commissioning editor', 'Ceramics designer',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Geologist, engineering', 'Designer, multimedia',
       'Engineer, manufacturing systems', 'Clinical embryologist',
       'Medical technical officer', 'Teacher, primary school',
       'Set designer', 'Producer, television/film/video',
       'Education officer, community',
       'Conservation officer, historic buildings',
       'Insurance account manager', 'Financial controller',
       'Film/video editor', 'Museum/gallery curator',
       'Accounting technician', 'Stage manager', 'Physiotherapist',
       'Sales promotion account executive', 'Horticultural consultant',
       'Journalist, broadcasting', 'Health and safety adviser',
       'Building services engineer',
       'Product/process development scientist', 'Metallurgist',
       'Audiological scientist', 'Designer, blown glass/stained glass',
       'Tax adviser', 'Industrial buyer',
       'Government social research officer',
       'Outdoor activities/education manager', 'Solicitor, Scotland',
       'Conference centre manager', 'Health physicist',
       'Pharmacist, community', 'Applications developer',
       'Public affairs consultant', 'Prison officer',
       'Production engineer', 'Actuary', 'Museum education officer',
       'Fitness centre manager', 'Records manager',
       'Journalist, newspaper', 'Computer games developer',
       'Toxicologist', 'Counsellor', 'Therapist, occupational',
       'Accountant, chartered certified', 'Insurance claims handler',
       'Programmer, applications', 'Accountant, chartered management',
       'Broadcast journalist', 'Energy manager', 'Barrister',
       'Scientist, audiological', 'Designer, graphic', 'Cartographer',
       'Community development worker', 'Engineer, mining',
       'Special effects artist', 'Gaffer', 'Civil Service administrator',
       'Armed forces training and education officer', 'Quality manager',
       'Engineer, electronics', 'Development worker, international aid',
       'Restaurant manager', 'Architectural technologist',
       'Academic librarian', 'Fast food restaurant manager',
       'Rural practice surveyor', 'Designer, ceramics/pottery',
       'Police officer', 'Soil scientist', 'Technical brewer',
       'Administrator, local government', 'Copywriter, advertising',
       'Volunteer coordinator', 'Magazine journalist',
       'Information officer', 'Copy', 'Advertising copywriter',
       'Engineer, biomedical', 'Nurse, learning disability',
       'Aeronautical engineer', 'Archaeologist', 'IT trainer',
       'Clinical biochemist',
       'Administrator, charities/voluntary organisations', 'Pathologist',
       'Geophysicist/field seismologist',
       'Investment banker, operational', 'Teacher, early years/pre',
       'Electronics engineer', 'Exhibitions officer, museum/gallery',
       'Nutritional therapist', 'Teaching laboratory technician',
       'Herbalist', 'Leisure centre manager', 'Higher education lecturer',
       'Newspaper journalist', 'Accountant, chartered',
       'Loss adjuster, chartered', 'Surveyor, commercial/residential',
       'Warehouse manager', 'Scientist, water quality',
       'Primary school teacher',
       'Chartered legal executive (England and Wales)',
       'Telecommunications researcher', 'Equality and diversity officer',
       'Learning mentor', 'Financial risk analyst',
       'Engineer, technical sales', 'Adult nurse'], dtype=object)

In [42]:
df_job = df[['Job', 'Purchase Price']]
df_job

                                         Job  Purchase Price
0     Scientist, product/process development           98.14
1                          Drilling engineer           70.73
2                   Customer service manager            0.95
3                          Drilling engineer           78.04
4                                Fine artist           77.82
...                                      ...             ...
9995                              Printmaker           82.21
9996                         Energy engineer           25.63
9997                      Veterinary surgeon           83.98
9998                Local government officer           38.84
9999                  Embryologist, clinical           67.59

[10000 rows x 2 columns]

In [55]:
df_job.groupby('Job')['Purchase Price'].mean() # 직업별 구매금액 평균

Job
Academic librarian                  47.951818
Accommodation manager               37.038235
Accountant, chartered               52.565500
Accountant, chartered certified     57.945000
Accountant, chartered management    69.082667
                                      ...
Water quality scientist             46.526111
Web designer                        59.764500
Wellsite geologist                  51.309167
Writer                              44.863000
Youth worker                        40.513333
Name: Purchase Price, Length: 623, dtype: float64

In [49]:
df_job.groupby('Job').sum().sort_values(by="Purchase Price")

                             Purchase Price
Job
Art gallery manager                  219.05
Marketing executive                  234.08
Information systems manager          241.42
Actuary                              262.72
Music therapist                      327.50
...                                     ...
Clinical cytogeneticist             1495.92
Therapist, art                      1526.31
Purchasing manager                  1577.97
Lawyer                              1603.85
Dietitian                           1605.30

[623 rows x 1 columns]

In [58]:
df_job.groupby('Job')['Purchase Price'].sum().sort_values(ascending=False)

Job
Dietitian                      1605.30
Lawyer                         1603.85
Purchasing manager             1577.97
Therapist, art                 1526.31
Clinical cytogeneticist        1495.92
                                ...
Music therapist                 327.50
Actuary                         262.72
Information systems manager     241.42
Marketing executive             234.08
Art gallery manager             219.05
Name: Purchase Price, Length: 623, dtype: float64

In [56]:
df_job.groupby('Job').sum().max()

Purchase Price    1605.3
dtype: float64

In [50]:
df[df['Email'] == 'bondellen@williams-garza.com']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1234,"2470 Maria Manors Suite 185\nJoneshaven, MN 87251",82 UX,PM,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.5.20) G...,"Cole, King and Bowers",4926535242672853,09/21,188,American Express,bondellen@williams-garza.com,Planning and development surveyor,159.182.3.50,ru,77.88

In [51]:
df[(df['CC Provider'] == 'Mastercard') & (df['Purchase Price'] >= 50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

In [52]:
len(df[(df['CC Provider'] == 'Mastercard') & (df['Purchase Price'] >= 50)])

405

In [53]:
df[df['Browser Info'].str.contains('Windows')]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
14,"8774 Jason Keys Suite 427\nEast Scottborough, ...",70 zH,AM,Mozilla/5.0 (Windows 98; it-IT; rv:1.9.2.20) G...,"Leach, Howe and Ferguson",869967499275071,09/22,427,VISA 16 digit,aburns@yahoo.com,Acupuncturist,50.25.148.1,de,24.18
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,"0154 Green Forest\nNew Timothy, IL 33670-4620",11 MC,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows 98;...,Williams-Walker,4207292109379681,10/16,571,Diners Club / Carte Blanche,hudsonmichael@pace.com,Charity fundraiser,136.169.160.82,de,89.76
9989,"5674 Cruz Trace\nNew Shelby, KY 51047-5469",12 Kf,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Vargas, Nichols and Martinez",5278049688438382,12/23,996,VISA 16 digit,walterswilliam@hotmail.com,Community development worker,39.162.164.169,pt,17.18
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63

In [54]:
len(df[df['Browser Info'].str.contains('Windows')])

4994

In [59]:
len(df[df['Browser Info'].str.contains('Linux')])

2322

In [60]:
len(df[df['Browser Info'].str.contains('Mac')])

2684